name: Validate JSON Files

on:
  push:
    paths:
      - '**/*.json'
  pull_request:
    paths:
      - '**/*.json'

jobs:
  validate-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install jsonlint
      run: npm install jsonlint -g

    - name: Validate JSON Files
      run: |
        # Determine which JSON files to validate
        if [ "${{ github.event_name }}" == "push" ]; then
          FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '*.json')
        elif [ "${{ github.event_name }}" == "pull_request" ]; then
          FILES=$(git diff --name-only origin/${{ github.base_ref }}..origin/${{ github.head_ref }} -- '*.json')
        fi

        # Loop through and validate each file
        for file in $FILES; do
          echo "Validating $file..."
          jsonlint -q $file || exit 1
        done
      shell: bash
